# Generated by Django 3.1.13 on 2021-11-17 21:25

import chalupa.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Chalupa Stoklaska', max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=chalupa.models.image_path, verbose_name='Image')),
                ('address', models.CharField(help_text='Ludvíkov 81', max_length=100, verbose_name='Address')),
                ('capacity', models.PositiveIntegerField(default='12', help_text='How many guests can be housed?')),
                ('price_per_night', models.PositiveIntegerField(default='1000', help_text='The cost per one night', verbose_name='Price per night')),
                ('private_bathroom', models.BooleanField(help_text='Does the guesthouse have a private bathroom?', verbose_name='Private bathroom')),
                ('number_of_rooms', models.PositiveIntegerField(default='3', help_text='How many rooms for guests does it have?', verbose_name='Number of rooms')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the room name', max_length=20, verbose_name='Room name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=chalupa.models.image_path, verbose_name='Image')),
                ('capacity', models.PositiveIntegerField(default='3', help_text='Enter the capacity of the room (extra beds included)')),
                ('extra_bed', models.BooleanField(default=False)),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalupa.bookingobject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=1)),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Od')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalupa.bookingobject')),
                ('user', models.ForeignKey(default='', help_text='Enter the name and surname', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=chalupa.models.attachment_path, verbose_name='File')),
                ('interior', models.BooleanField(verbose_name='Does the photo display interior?')),
                ('exterior', models.BooleanField(verbose_name='Does the photo display exterior?')),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalupa.bookingobject')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalupa.room')),
            ],
            options={
                'order_with_respect_to': 'room',
            },
        ),
    ]
