# Generated by Django 3.1.13 on 2021-11-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('modry', 'Modrý pokoj'), ('zeleny', 'Zelený pokoj'), ('oranzovy', 'Oranžový pokoj')], help_text='Enter the room name', max_length=20, verbose_name='Room name')),
                ('capacity', models.PositiveIntegerField(default='3', help_text='Enter the capacity of the room (extra beds included)')),
                ('extra_bed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=1)),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Od')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(default='', help_text='Enter the name and surname', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
