# Generated by Django 3.1.13 on 2021-11-14 19:33

import chalupa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalupa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chalupa.models.image_path, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=chalupa.models.attachment_path, verbose_name='File')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalupa.room')),
            ],
            options={
                'order_with_respect_to': 'room',
            },
        ),
    ]
