# Generated by Django 3.1.13 on 2021-12-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chalupa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='booking_object',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_object',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booking_object',
        ),
        migrations.DeleteModel(
            name='BookingObject',
        ),
    ]
