# Generated by Django 3.1.13 on 2021-11-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalupa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chalupa.room'),
        ),
    ]
