# Generated by Django 3.1.13 on 2021-11-28 20:13

import chalupa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalupa', '0002_auto_20211128_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(null=True, upload_to=chalupa.models.attachment_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chalupa.room'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='attachment',
            order_with_respect_to='title',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='exterior',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='last_update',
        ),
    ]
